name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run type-check

      - name: Unit tests
        run: |
          npm run test

      - name: Package tests
        working-directory: ./tests
        run: |
          npm run preparing
          npm run test
